/**
 * Monthly PF (ECR) and ESI statutory return rows — pure, Prisma-free.
 *
 * Both returns are derived from the FROZEN figures on HrSalaryRunLine, never a
 * recomputation, so a filed month can always be regenerated byte-for-byte even
 * after statutory rules change. Column layouts mirror the sheets DESMA already
 * uploads to the EPFO / ESIC portals (August 2026 reference files), including
 * header wording — do not "fix" spacing or the double space in
 * "EPF EPS Difference  remitted"; the portal-side templates have them.
 *
 * Two line generations exist in production:
 *   - lines computed BEFORE the PF statutory-rules feature (PR #338) have the
 *     PF audit columns (pfWage, pfEmployerEpf/Eps, pfDetail) at their zero
 *     defaults. They are recognised by pfDetail == null and their ECR split is
 *     derived here from basicAfterLop + the stored employee/employer totals
 *     under the legacy ₹15,000 / 8.33% maths those lines were computed with;
 *   - newer lines carry the frozen audit columns, which are used as-is.
 *
 * EPS-exempt members (Employee.epsExempt): the ECR shows EPS wage/contribution
 * 0 with the whole employer share in the EPF-EPS-difference column. Applied
 * here at report time as well, so runs frozen before the flag was set still
 * file correctly — it only ever reallocates between the two employer columns.
 */

const round = (n: number) => Math.round(n);
const round2 = (n: number) => Math.round(n * 100) / 100;

/** Ceiling + EPS rate the pre-rules engine hard-coded (legacy lines only). */
const LEGACY_PF_CEILING = 15000;
const LEGACY_EPS_RATE_PCT = 8.33;
/**
 * EDLI wages stay capped at ₹15,000 — the EDLI ceiling is set by its own
 * scheme and did NOT move with the 17 Sep 2026 PF wage-ceiling revision.
 */
const EDLI_WAGE_CEILING = 15000;

/** ESI stops applying above this gross (mirrors isEsiApplicable in the engine). */
export const ESI_GROSS_CEILING = 21000;

/** ECR sheet header — exact wording of the sheet the EPFO portal flow uses. */
export const ECR_HEADER = [
  "UAN No",
  "Member Name",
  "Gross Wages",
  "EPF Wages",
  "EPS Wage",
  "EDLI Wages",
  "EPF Contribution Remitted",
  "EPS Contribution remitted",
  "EPF EPS Difference  remitted",
  "NCP Days",
  "Refund of Advances",
] as const;

/** ESI upload header — exact wording of the ESIC monthly-payment template. */
export const ESI_HEADER = [
  "IP Number \n(10 Digits)",
  "IP Name\n( Only alphabets and space )",
  "No of Days for which wages paid/payable during the month",
  "Total Monthly Wages",
  " Reason Code for Zero workings days(numeric only; provide 0 for all other reasons- Click on the link for reference)",
  " Last Working Day\n( Format DD/MM/YYYY  or DD-MM-YYYY)",
] as const;

/** The slice of a salary-run line + employee the derivations need. */
export type StatutoryLineInput = {
  employeeId: string;
  empCode: string;
  name: string;
  uan: string | null;
  esiIpNumber: string | null;
  epsExempt: boolean;
  /** Earned gross after LOP (the ESI wage and the ECR "Gross Wages"). */
  salaryBeforeEsi: number;
  /** LOP-reduced basic — PF wage source for legacy (pre-audit) lines. */
  basicAfterLop: number;
  /** Paid days (working-days base − LOP). */
  daysAttended: number;
  /** LOP days = the ECR NCP days. */
  totalLeaveForLop: number;
  /** Stored employee PF deduction (statutory + VPF — ECR EE share includes VPF). */
  pfEmployee: number;
  /** Stored employer PF total (EPF + EPS). */
  pfEmployer: number;
  /** Frozen PF audit columns; zero defaults on legacy lines. */
  pfWage: number;
  pfEmployerEpf: number;
  pfEmployerEps: number;
  /** Frozen per-segment snapshot; null marks a legacy (pre-audit) line. */
  pfDetail: { segments?: { segmentWage?: number; proratedCeiling?: number }[] } | null;
};

export type EcrRow = {
  employeeId: string;
  empCode: string;
  uan: string;
  name: string;
  grossWages: number;
  epfWages: number;
  epsWage: number;
  edliWages: number;
  /** Employee share remitted (incl. VPF). */
  epfContribution: number;
  /** Employer share diverted to EPS. */
  epsContribution: number;
  /** Employer share credited to EPF (the "EPF EPS Difference" column). */
  epfEpsDifference: number;
  ncpDays: number;
  refundOfAdvances: number;
};

export type EsiRow = {
  employeeId: string;
  empCode: string;
  ipNumber: string;
  name: string;
  daysPaid: number;
  monthlyWages: number;
  /** True when no wages were paid — the portal wants a reason code + LWD. */
  zeroDays: boolean;
};

/** One employee's ECR figures from a frozen salary-run line. */
export function deriveEcrRow(line: StatutoryLineInput): EcrRow {
  const legacy = line.pfDetail == null;
  const pfWage = legacy ? round2(Math.min(line.basicAfterLop, LEGACY_PF_CEILING)) : line.pfWage;

  // EPS wage = the ceiling-capped slice of the PF wage. New lines rebuild it
  // from the frozen per-segment snapshot (a transition cycle prorates the
  // ceiling per segment); legacy lines were always ceiling-capped already.
  let epsWage: number;
  let eps: number;
  let epf: number;
  if (legacy) {
    epsWage = pfWage;
    eps = Math.min(round((epsWage * LEGACY_EPS_RATE_PCT) / 100), round(line.pfEmployer));
    epf = round(line.pfEmployer) - eps;
  } else {
    const segments = line.pfDetail?.segments ?? [];
    const cappedSum = segments.reduce(
      (sum, s) => sum + Math.min(s.segmentWage ?? 0, s.proratedCeiling ?? 0),
      0,
    );
    epsWage = segments.length > 0 ? round2(cappedSum) : round2(Math.min(pfWage, LEGACY_PF_CEILING));
    eps = round(line.pfEmployerEps);
    epf = round(line.pfEmployerEpf);
  }

  // EPS-exempt member: the whole employer share is EPF. Applied at report
  // time too, so lines frozen before the flag was set still file correctly.
  if (line.epsExempt || eps === 0) {
    epf += eps;
    eps = 0;
    epsWage = 0;
  }

  return {
    employeeId: line.employeeId,
    empCode: line.empCode,
    uan: (line.uan ?? "").trim(),
    name: line.name,
    grossWages: round2(line.salaryBeforeEsi),
    epfWages: pfWage,
    epsWage,
    edliWages: round2(Math.min(pfWage, EDLI_WAGE_CEILING)),
    epfContribution: round(line.pfEmployee),
    epsContribution: eps,
    epfEpsDifference: epf,
    ncpDays: line.totalLeaveForLop,
    refundOfAdvances: 0,
  };
}

/** One employee's ESI figures from a frozen salary-run line. */
export function deriveEsiRow(line: StatutoryLineInput): EsiRow {
  return {
    employeeId: line.employeeId,
    empCode: line.empCode,
    ipNumber: (line.esiIpNumber ?? "").trim(),
    name: line.name,
    daysPaid: line.daysAttended,
    monthlyWages: round(line.salaryBeforeEsi),
    zeroDays: line.daysAttended <= 0,
  };
}

/** "2026-08" → "August 2026" (for filenames and page copy). */
export function monthLabel(monthKey: string): string {
  const [y, m] = monthKey.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, 1)).toLocaleDateString("en-IN", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

/** Format a day count the way the upload sheets carry it ("27", "27.5"). */
export function formatDays(days: number): string {
  return Number.isInteger(days) ? String(days) : String(round2(days));
}
