/**
 * Snapshot of `Candidate list.xlsx` (Sheet1) as of 2026-05-11.
 *
 * The user-facing /master-data/parties "Run candidate import" button
 * reads this list — bundling the data in code keeps the import
 * deterministic + lets us re-run it from a Vercel-deployed environment
 * without needing file-upload plumbing.
 *
 * Rows with the same candidate name are merged into one Party with
 * multiple PartyService rows (one per service). totalAmount is set to
 * the Excel value when present, else 0. Trailing whitespace in names
 * has been stripped here.
 *
 * Service-name aliases (Excel label → Service master name):
 *   "PTE Registration"          → "PTE Coaching"
 *   "Study Abroad Registration" → "Study Abroad - Registration Fee"
 *
 * "Attestation Charge" and "GCAN" don't match any existing Service —
 * the import endpoint creates them on the fly via upsert.
 */
export type CandidateImportRow = {
  name: string;
  service: string;
  totalAmount: number;
};

export const CANDIDATE_IMPORT_ROWS: CandidateImportRow[] = [
  { name: "Sagara Antony", service: "ANMAC Skills Assessment", totalAmount: 29500 },
  { name: "Remya Narayanan", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "P R Parvathy", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Leemsiya", service: "ANMAC + PR", totalAmount: 106200 },
  { name: "Monu Varghese", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Nancy Joy", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Maggie Nelson", service: "AHPRA New Streamlined Pathway", totalAmount: 59000 },
  { name: "Ansa V Alias", service: "ANMAC + PR", totalAmount: 118000 },
  { name: "Alice Varghese", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Honey Raj", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Devikrishna", service: "RN Visa Processing", totalAmount: 29500 },
  { name: "Sharmi Joseph", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Tessy Thomas", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Daniel John", service: "AHPRA OBA Pathway", totalAmount: 106200 },
  { name: "Mariya Biju", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Chinnumol Binoy", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Maneesha Mambra", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Anila Vijayan", service: "ANMAC + PR", totalAmount: 0 },
  { name: "Hilal Muhammad Muhammad Kunju", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Soumya Ponnamma", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Anila Vijayan", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Deepa Edanjalil", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Josmy Sebastian", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Ann Mary George", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Dhanya Jose", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Reshma Raj", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Jemin James", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Anju Kizhakkayil Jose", service: "PTE Coaching", totalAmount: 4999 },
  { name: "Anumol Xavier", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Nikita John", service: "Attestation", totalAmount: 0 },
  { name: "Jisty George", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Mariya Johny", service: "ANMAC + PR", totalAmount: 29500 },
  { name: "Nisha Paul", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Angel Treesa Prince", service: "Study Abroad - Registration Fee", totalAmount: 0 },
  { name: "Malavika Ambadath Sivanandhan", service: "AHPRA New Streamlined Pathway", totalAmount: 59000 },
  { name: "Arsha Chithiranivas Pavithran", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Mariya Regi", service: "Attestation", totalAmount: 0 },
  { name: "Rinu Krishnan R", service: "New Zealand Pathway to Australia", totalAmount: 121540 },
  { name: "Athiramol", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Nisha Rajan", service: "Attestation", totalAmount: 0 },
  { name: "Jilu Anna John", service: "AHPRA Final Registration Support", totalAmount: 0 },
  { name: "Aleena Joseph", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Jancy Chacko", service: "AHPRA OBA Pathway", totalAmount: 106200 },
  { name: "Athulya T Jose", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Sinimol", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Navya Poulose", service: "OSCE Visa + Final Registration", totalAmount: 88500 },
  { name: "Jancy Louise", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Merin Abraham", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Delhia David", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Ashly Binoy", service: "PTE Coaching", totalAmount: 0 },
  { name: "Bini Kuriakose", service: "AHPRA Till NCLEX", totalAmount: 41300 },
  { name: "Mariya Regi", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Hebsiba", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Cilu Ann Abraham", service: "AHPRA Till NCLEX", totalAmount: 41300 },
  { name: "Hari Prasad JS", service: "AHPRA New Streamlined Pathway", totalAmount: 59000 },
  { name: "Sijo Thomas", service: "AHPRA Till NCLEX", totalAmount: 41300 },
  { name: "Subi Babu", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Steephan Thekkanath Sebastian", service: "ANMAC + PR", totalAmount: 106200 },
  { name: "Anju Vazhappilly Thomas", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Seena K Jose", service: "PTE Coaching", totalAmount: 0 },
  { name: "Hima P Das", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Ashly Salam Abdul Salam", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Athira Radhamany", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Athira Jagadamma", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Jipsa Thomas", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Abhner Clottilda", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Hari Prasad JS", service: "Attestation", totalAmount: 0 },
  { name: "Malavika Ambadath Sivanandhan", service: "Attestation", totalAmount: 0 },
  { name: "Jitty Maria Mathew", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Ajips Esakiel", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Ardhra Raju", service: "ANMAC + PR", totalAmount: 118000 },
  { name: "Praveena Arul", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Simcymol Sunny", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Narmatha Mohanan", service: "ANMAC + PR", totalAmount: 106200 },
  { name: "Manisha Maria Manoj", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Aswathydevi Shajimon", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Anu Wilson", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "ENATEWET K AFAGE", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Sijo Thomas", service: "Attestation", totalAmount: 0 },
  { name: "Linta Lalan", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Bibisha DS", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Hebsiba", service: "ANMAC + PR", totalAmount: 0 },
  { name: "Renjini Theeyanil Rajan", service: "New Zealand Pathway to Australia", totalAmount: 121540 },
  { name: "Alveena Reji", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Chithra C C", service: "ANMAC + PR", totalAmount: 0 },
  { name: "Keziah Joseph", service: "AHPRA New Streamlined Pathway", totalAmount: 59000 },
  { name: "Amala mani", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Reshma Chenapuravan", service: "New Zealand Pathway to Australia", totalAmount: 0 },
  { name: "Leena Jomon", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Chithra Palaparambath", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Neenu Mathew", service: "AHPRA New Streamlined Pathway", totalAmount: 59000 },
  { name: "Prapitha Gopi", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Soumya Paulose", service: "New Zealand Pathway to Australia", totalAmount: 0 },
  { name: "Anusha varampettan", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Neethu Paul", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Athira Madhu jayakumari", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "MWT Australia", service: "GCAN", totalAmount: 2400 },
  { name: "Banupriya Balusamy", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Nimya Rajan", service: "ANMAC + PR", totalAmount: 118000 },
  { name: "Malu Nadesh", service: "RN Visa Processing", totalAmount: 0 },
  { name: "Vijina Kumbla", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Anni Sibi", service: "PTE Coaching", totalAmount: 0 },
  { name: "Haripriya K", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Feby Chennamkara", service: "AHPRA Till NCLEX", totalAmount: 41300 },
  { name: "Krishnapriya S", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Neenu Mathew", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Amalu C J", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Arya Babu", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Lisna joseph", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Florence Melani Fernandes", service: "AHPRA OBA Pathway", totalAmount: 106200 },
  { name: "Anu Tom", service: "ANMAC + PR", totalAmount: 29500 },
  { name: "Jolly Mathew", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Srijila Kunnummal Meethal", service: "ANMAC + PR", totalAmount: 0 },
  { name: "Malavika Ambadath Sivanandhan", service: "AHPRA New Streamlined Pathway", totalAmount: 0 },
  { name: "Renjini Theeyanil Rajan", service: "New Zealand Pathway to Australia", totalAmount: 0 },
  { name: "Srijila", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Neenu Johnson", service: "AHPRA OBA Pathway", totalAmount: 109740 },
  { name: "Lesly Mariam Thomas", service: "AHPRA OBA Pathway", totalAmount: 118000 },
  { name: "Megha Lal M B", service: "IELTS Coaching", totalAmount: 0 },
  { name: "Nisha Nidheesh", service: "Renewal Service Charge", totalAmount: 0 },
  { name: "Leena Philip", service: "OSCE Visa + Final Registration", totalAmount: 2900 },
  { name: "Leenu Philip", service: "OSCE Visa + Final Registration", totalAmount: 2900 },
  { name: "Ashly Salam Abdul Salam", service: "AHPRA OBA Pathway", totalAmount: 0 },
  { name: "Betzy Malampara Philip", service: "AHPRA OBA Pathway", totalAmount: 121540 },
  { name: "Sneha Achamma Thomas", service: "AHPRA Till NCLEX", totalAmount: 41300 },
  { name: "Priyanka Jijo", service: "New Zealand Pathway to Australia", totalAmount: 121540 },
];
