import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#004782",
        "primary-container": "#185fa5",
        "on-primary": "#ffffff",
        "on-primary-container": "#c1d9ff",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        secondary: "#5c5f61",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0e3e5",
        "on-secondary-container": "#626567",
        "secondary-fixed-dim": "#c4c7c9",
        tertiary: "#6f3800",
        surface: "#f8f9ff",
        "surface-dim": "#d9dae0",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3fa",
        "surface-container": "#ededf4",
        "surface-container-high": "#e7e8ee",
        "surface-container-highest": "#e1e2e9",
        "surface-variant": "#e1e2e9",
        "on-surface": "#191c20",
        "on-surface-variant": "#424751",
        outline: "#727782",
        "outline-variant": "#c2c6d2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        margin: "32px",
      },
      fontSize: {
        h1: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
