import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Privacy Policy — Desgro | DESMA International Private Limited",
  description:
    "Privacy Policy for the Desgro application and desgro.in, explaining how DESMA International Private Limited collects, uses and protects personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className={styles.page}>
      <div className={styles.wrap}>
        <header className={styles.header}>
          <h1 className={styles.h1}>Privacy Policy</h1>
          <p className={styles.dates}>Effective date: 1 August 2026 · Last updated: 1 August 2026</p>
        </header>

        <h2 id="who-we-are" className={styles.h2}>1. Who we are</h2>
        <p>
          This Privacy Policy explains how <strong>DESMA International Private Limited</strong> (“DESMA
          International”, “we”, “us”, “our”) collects, uses, shares and protects personal data in connection with
          the <strong>Desgro</strong> application (Meta App ID <code>1074053418482215</code>) and the services made
          available at <a href="https://www.desgro.in">https://www.desgro.in</a> (together, the “Service”).
        </p>
        <p className={styles.idblock}>
          <strong>Registered address:</strong> XVI 195/C, First Floor, Keltron Road, Aroor, Kerala 688534, India
          <br />
          <strong>CIN:</strong> U70200KL2023PTC084811
          <br />
          <strong>GSTIN:</strong> 32AAKCD4674Q1Z1
          <br />
          <strong>Contact:</strong> <a href="mailto:hello@desma.in">hello@desma.in</a>
        </p>
        <p>
          Desgro is a business application used by DESMA International to manage customer communications and
          enquiries. It connects to Meta Platforms services — the WhatsApp Business Platform (Cloud API), Facebook
          Pages and Messenger, Instagram, and the Meta Marketing API — so that messages and enquiries reaching those
          channels are delivered into our customer relationship management (CRM) system.
        </p>
        <p>
          We act as the <strong>data controller</strong> (a “Data Fiduciary” under India&rsquo;s Digital Personal
          Data Protection Act, 2023) for the personal data described in this policy.
        </p>

        <h2 id="what-it-does" className={styles.h2}>2. What the Service does</h2>
        <p>
          When you message one of our WhatsApp business numbers, our Facebook Page, or our Instagram account, or
          when you submit a lead form on one of our advertisements, Meta delivers that interaction to our
          application. Our application records it in our CRM so that a member of our team can respond to you and
          keep track of the conversation.
        </p>
        <p>We do not use the Service to send unsolicited marketing to people who have not contacted us or opted in.</p>

        <h2 id="what-we-collect" className={styles.h2}>3. Information we collect</h2>

        <h3 className={styles.h3}>3.1 Information you give us directly</h3>
        <ul>
          <li>Your name, phone number and email address, when you provide them</li>
          <li>The content of the messages, images, documents, voice notes and other media you send us</li>
          <li>Information you enter into a lead form or contact form</li>
          <li>Any other information you choose to share in the course of a conversation</li>
        </ul>

        <h3 className={styles.h3}>3.2 Information we receive from Meta Platforms</h3>
        <p>Depending on which channel you use to contact us, Meta provides us with:</p>
        <ul>
          <li>
            <strong>WhatsApp:</strong> your WhatsApp phone number, your WhatsApp profile display name, the content
            and timestamps of messages you send to our business number, and delivery/read status of messages we
            send you
          </li>
          <li>
            <strong>Messenger and Instagram:</strong> your platform-scoped user ID, your public profile name and
            profile picture, and the content and timestamps of messages you exchange with us
          </li>
          <li><strong>Facebook Pages:</strong> comments, reactions and enquiries you post on our Page</li>
          <li>
            <strong>Lead ads:</strong> the fields you complete in a Meta lead generation form, such as name, phone
            number, email address and any custom questions we ask
          </li>
          <li>
            <strong>Marketing API:</strong> aggregated and de-identified advertising performance data, which is
            statistical and does not identify you individually
          </li>
        </ul>

        <h3 className={styles.h3}>3.3 Technical information</h3>
        <ul>
          <li>Log data generated by our servers, including timestamps, request identifiers and error records</li>
          <li>Basic security and diagnostic information needed to keep the Service running</li>
        </ul>
        <p>
          We do <strong>not</strong> collect payment card details, government identification numbers, precise
          location, or biometric data through the Service.
        </p>

        <h2 id="how-we-use" className={styles.h2}>4. How we use your information</h2>
        <ul>
          <li>Receive, read and respond to your messages and enquiries</li>
          <li>
            Maintain a record of our conversation so that any member of our team can assist you without asking you
            to repeat yourself
          </li>
          <li>Send you information, quotations, order updates and service messages you have requested or consented to receive</li>
          <li>Provide customer support and resolve complaints</li>
          <li>Keep records required for our legitimate business and accounting purposes</li>
          <li>Detect, prevent and investigate fraud, abuse and security incidents</li>
          <li>Comply with applicable law and respond to lawful requests from authorities</li>
        </ul>
        <p>We do <strong>not</strong> sell your personal data, and we do not share it with third parties for their own advertising purposes.</p>

        <h2 id="legal-basis" className={styles.h2}>5. Legal basis for processing</h2>
        <p>Where the law requires us to identify a legal basis, we rely on:</p>
        <ul>
          <li>
            <strong>Consent</strong> — you initiate contact with us and provide your information voluntarily; for
            WhatsApp, by messaging our business number you consent to us receiving and responding to that message
          </li>
          <li><strong>Performance of a contract</strong> — where we are processing an order, quotation or service request</li>
          <li><strong>Legitimate interests</strong> — operating and securing our business, keeping accurate customer records, and improving our service</li>
          <li><strong>Legal obligation</strong> — where retention or disclosure is required by law</li>
        </ul>
        <p>You may withdraw consent at any time (see Section 9). Withdrawal does not affect processing carried out before withdrawal.</p>

        <h2 id="sharing" className={styles.h2}>6. How we share information</h2>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Recipient</th>
              <th>Purpose</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>Meta Platforms, Inc. / Meta Platforms Ireland Ltd.</strong></td>
              <td>
                Meta operates WhatsApp, Messenger, Instagram and Facebook and necessarily processes your messages in
                order to transmit them. Meta&rsquo;s own handling of your data is governed by its privacy policies,
                linked in Section 13.
              </td>
            </tr>
            <tr>
              <td><strong>Hosting and infrastructure providers</strong></td>
              <td>To host our CRM and application servers</td>
            </tr>
            <tr>
              <td><strong>Business solution providers</strong></td>
              <td>We use authorised WhatsApp Business Solution Providers to help operate our WhatsApp channel. They process message data on our instructions only.</td>
            </tr>
            <tr>
              <td><strong>Professional advisers</strong></td>
              <td>Lawyers, accountants and auditors, where necessary and under a duty of confidentiality</td>
            </tr>
            <tr>
              <td><strong>Authorities</strong></td>
              <td>Where disclosure is required by law, court order or a valid legal request</td>
            </tr>
            <tr>
              <td><strong>A successor entity</strong></td>
              <td>If our business is merged, acquired or reorganised, subject to this policy continuing to apply</td>
            </tr>
          </tbody>
        </table>
        <p>All service providers who process data on our behalf are bound by contract to use it only for the purposes we specify and to keep it secure.</p>

        <h2 id="transfers" className={styles.h2}>7. International transfers</h2>
        <p>
          Meta and some of our service providers operate servers outside India. Where personal data is transferred
          outside your country, we take reasonable steps to ensure it remains protected to a standard consistent
          with this policy and applicable law, including through contractual safeguards with our processors.
        </p>

        <h2 id="retention" className={styles.h2}>8. How long we keep your information</h2>
        <ul>
          <li><strong>Message and conversation records:</strong> 24 months from the date of last contact</li>
          <li><strong>Customer and order records:</strong> 8 years from the end of the relevant financial year, in line with Indian tax, GST and companies law record-keeping requirements</li>
          <li><strong>Lead records that do not convert:</strong> 12 months from the date the lead was received</li>
          <li><strong>Server and security logs:</strong> 90 days</li>
        </ul>
        <p>
          After these periods we delete the data or irreversibly anonymise it, unless a longer period is required
          by law or is necessary to establish, exercise or defend a legal claim.
        </p>

        <h2 id="data-deletion" className={styles.h2}>9. Your rights and how to exercise them</h2>

        <h3 className={styles.h3}>Your rights</h3>
        <p>Subject to applicable law, you have the right to:</p>
        <ul>
          <li><strong>Access</strong> — obtain a copy of the personal data we hold about you</li>
          <li><strong>Correction</strong> — ask us to correct data that is inaccurate, incomplete or out of date</li>
          <li><strong>Erasure</strong> — ask us to delete your personal data</li>
          <li><strong>Withdraw consent</strong> — stop us processing data that we process on the basis of consent</li>
          <li><strong>Restriction and objection</strong> — ask us to limit or stop certain processing</li>
          <li><strong>Portability</strong> — receive your data in a structured, machine-readable format, where applicable</li>
          <li><strong>Grievance redressal</strong> — raise a complaint with us and receive a response</li>
          <li><strong>Nominate</strong> — under India&rsquo;s DPDP Act, 2023, nominate a person to exercise your rights in the event of your death or incapacity</li>
        </ul>

        <h3 className={styles.h3}>Data deletion instructions</h3>
        <div className={styles.note}>
          <p>
            To request deletion of the personal data we hold about you, email{" "}
            <strong><a href="mailto:hello@desma.in">hello@desma.in</a></strong> with the subject line{" "}
            <strong>“Data Deletion Request”</strong>, or send a WhatsApp message containing the word{" "}
            <strong>DELETE</strong> to the business number you have been corresponding with.
          </p>
        </div>
        <ol>
          <li>Send the request as described above.</li>
          <li>Tell us the phone number, email address or account name you used to contact us, so we can locate your records.</li>
          <li>We will verify that the request comes from you or someone authorised to act for you.</li>
          <li>We will delete your personal data within <strong>30 days</strong> of verifying the request and confirm to you once it is done.</li>
        </ol>
        <p>
          We may need to retain a minimal record of the deletion request itself, and any data we are legally
          required to keep — for example invoices required under tax law. We will tell you if this applies and
          explain what has been retained and why.
        </p>
        <p>
          Deleting data from our systems does not delete the message history stored in your own WhatsApp, Messenger
          or Instagram app, and does not delete data held by Meta. To manage data held by Meta, use the tools in
          Section 13.
        </p>

        <h3 className={styles.h3}>Grievance Officer</h3>
        <p>
          If you are not satisfied with how we have handled your data or your request, contact:
          <br />
          <strong>Grievance Officer:</strong> Shibin Raj
          <br />
          <strong>Email:</strong> <a href="mailto:hello@desma.in">hello@desma.in</a>
          <br />
          <strong>Address:</strong> DESMA International Private Limited, XVI 195/C, First Floor, Keltron Road,
          Aroor, Kerala 688534, India
        </p>
        <p>
          We will acknowledge your complaint within 7 working days and aim to resolve it within 30 days. If you
          remain dissatisfied, you may escalate to the Data Protection Board of India, or to your local supervisory
          authority if you are in the EU or UK.
        </p>

        <h2 id="security" className={styles.h2}>10. Security</h2>
        <ul>
          <li>Encryption of data in transit using TLS/HTTPS</li>
          <li>Access controls limiting CRM access to authorised personnel on a need-to-know basis</li>
          <li>Verification of the authenticity of webhook requests received from Meta</li>
          <li>Secure storage of API credentials and access tokens, which are never shared outside our organisation</li>
          <li>Logging and monitoring of access to personal data</li>
        </ul>
        <p>
          No method of transmission or storage is completely secure. While we work to protect your data, we cannot
          guarantee absolute security. If a breach occurs that is likely to result in a risk to you, we will notify
          you and the relevant authorities as required by law.
        </p>

        <h2 id="children" className={styles.h2}>11. Children</h2>
        <p>
          The Service is not directed at children and we do not knowingly collect personal data from anyone under
          the age of 18. If you believe a child has provided us with personal data, contact us at{" "}
          <a href="mailto:hello@desma.in">hello@desma.in</a> and we will delete it.
        </p>

        <h2 id="automated" className={styles.h2}>12. Automated decision-making</h2>
        <p>We do not use your personal data to make decisions about you by purely automated means that produce legal or similarly significant effects.</p>

        <h2 id="meta" className={styles.h2}>13. Meta&rsquo;s own privacy practices</h2>
        <p>When you communicate with us through Meta&rsquo;s platforms, Meta processes your data under its own policies, which we do not control:</p>
        <ul>
          <li><a href="https://www.whatsapp.com/legal/privacy-policy">WhatsApp Privacy Policy</a></li>
          <li><a href="https://www.facebook.com/privacy/policy/">Meta Privacy Policy</a></li>
          <li><a href="https://privacycenter.instagram.com/policy">Instagram Data Policy</a></li>
        </ul>
        <p>You can review and manage the data Meta holds about you in your Meta Accounts Center settings.</p>

        <h2 id="changes" className={styles.h2}>14. Changes to this policy</h2>
        <p>
          We may update this policy from time to time. When we do, we will revise the “Last updated” date at the
          top of this page. If the changes are significant, we will take reasonable steps to notify you — for
          example by a message on the channel you use to contact us. Please review this page periodically.
        </p>

        <h2 id="contact" className={styles.h2}>15. Contact us</h2>
        <p>
          Questions, requests or complaints about this policy or your personal data:
          <br />
          <br />
          <strong>DESMA International Private Limited</strong>
          <br />
          XVI 195/C, First Floor, Keltron Road, Aroor, Kerala 688534, India
          <br />
          CIN: U70200KL2023PTC084811 · GSTIN: 32AAKCD4674Q1Z1
          <br />
          Email: <a href="mailto:hello@desma.in">hello@desma.in</a>
          <br />
          Website: <a href="https://www.desgro.in">https://www.desgro.in</a>
        </p>

        <footer className={styles.footer}>
          This policy applies to the Desgro application (Meta App ID 1074053418482215) and the services at desgro.in.
        </footer>
      </div>
    </div>
  );
}
