import {
  BaseBankStatementParser,
  SLASH_DATE,
  amountOf,
  parseSlashDate,
  reconcileDirections,
  tokenize,
  type Line,
  type ParsedRow,
  type ParsedStatement,
  type StatementSummary,
  type TextItem,
} from "./base";
import { isAmountToken, type Paise } from "../money";

/**
 * HDFC Bank account statement (the SmartStatement / e-mail statement PDF).
 *
 * Layout, per page:
 *   Date | Narration | Chq./Ref.No. | Value Dt | Withdrawal Amt. | Deposit Amt. | Closing Balance
 *   06/10/26  UPI-NAME-VPA@BANK-…     0000123456789012  06/10/26  1,250.00            98,750.00
 *             …narration continues on following lines…
 * and once, at the end:
 *   STATEMENT SUMMARY :-
 *   Opening Balance  Dr Count  Cr Count  Debits  Credits  Closing Bal
 *   1,00,000.00      1         0         1,250.00 0.00    98,750.00
 * plus a header block with "Account No :…" and "From : dd/mm/yyyy To : dd/mm/yyyy".
 *
 * Two strategies: `columns` places every text item by the x-position of the
 * page's column headers (handles multi-line narrations and an empty
 * withdrawal/deposit cell exactly); `text` is the fallback that reads each
 * line as a string and leans on the running balance for direction.
 */

const FOOTER =
  /^(STATEMENT SUMMARY|\*?Closing balance includes|Contents of this statement|Generated On|Generated By|Requesting Branch|This is a computer generated|HDFC BANK LIMITED|State account branch|Registered Office|Page No|GSTN|GSTIN|\*+\s*End of Statement)/i;

type ColKey = "date" | "narration" | "ref" | "valueDate" | "debit" | "credit" | "balance";
type Columns = Record<ColKey, { left: number; right: number }>;

const HEADER_MATCH: Array<[ColKey, RegExp]> = [
  ["date", /^Date$/i],
  ["narration", /^Narration/i],
  ["ref", /^(Chq|Ref)/i],
  ["valueDate", /^Value/i],
  ["debit", /^(Withdrawal|Debit)/i],
  ["credit", /^(Deposit|Credit)/i],
  ["balance", /^(Closing|Balance)/i],
];

/**
 * The column-header band. HDFC's header often wraps ("Withdrawal" over
 * "Amt.", "Closing" over "Balance"), so a header is the run of adjacent
 * header-looking lines around the one that says "Narration", read together.
 */
export type HeaderBand = { start: number; end: number; text: string; cols: Columns | null };

function headerish(line: Line): boolean {
  const toks = tokenize(line.items);
  return line.text.length < 220 && !toks.some((t) => SLASH_DATE.test(t.str) || isAmountToken(t.str));
}

export function findHeaderBands(lines: Line[]): HeaderBand[] {
  const bands: HeaderBand[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (!/Narration/i.test(lines[i].text) || !headerish(lines[i])) continue;
    let s = i;
    let e = i;
    const near = (a: Line, b: Line) => a.page === b.page && Math.abs(a.y - b.y) <= 12;
    while (s > 0 && near(lines[s - 1], lines[s]) && headerish(lines[s - 1])) s--;
    while (e < lines.length - 1 && near(lines[e + 1], lines[e]) && headerish(lines[e + 1])) e++;
    const band = lines.slice(s, e + 1);
    const text = band.map((l) => l.text).join(" ");
    if (/(Withdrawal|Debit)/i.test(text) && /Balance/i.test(text)) {
      bands.push({ start: s, end: e, text, cols: columnsFromHeader(tokenize(band.flatMap((l) => l.items))) });
    }
    i = e;
  }
  return bands;
}

/** Column anchors from the header band's tokens, or null when they are not the expected seven in order. */
export function columnsFromHeader(tokens: TextItem[]): Columns | null {
  const sorted = [...tokens].sort((a, b) => a.x - b.x || a.y - b.y);
  const used = new Set<TextItem>();
  const found: Partial<Columns> = {};
  for (const [key, re] of HEADER_MATCH) {
    const it = sorted.find((t) => !used.has(t) && re.test(t.str));
    if (!it) return null;
    used.add(it);
    found[key] = { left: it.x, right: it.x + it.w };
  }
  const keys = HEADER_MATCH.map(([k]) => k);
  const cols = found as Columns;
  for (let i = 1; i < keys.length; i++) {
    if (cols[keys[i]].left <= cols[keys[i - 1]].left) return null;
  }
  // A column's right edge is the furthest-right header word under it — right-aligned
  // amounts line up with that edge, whichever line of the wrapped header it is on.
  for (let i = 0; i < keys.length; i++) {
    const lo = cols[keys[i]].left - 3;
    const hi = i + 1 < keys.length ? cols[keys[i + 1]].left - 3 : Infinity;
    for (const t of tokens) {
      if (t.x >= lo && t.x < hi) cols[keys[i]].right = Math.max(cols[keys[i]].right, t.x + t.w);
    }
  }
  return cols;
}

/** Which column a body token belongs to. Amounts are right-aligned, so they snap by right edge. */
function columnOf(it: TextItem, c: Columns): ColKey {
  const s = it.str;
  const right = it.x + it.w;
  if (isAmountToken(s) && right > c.debit.left - 2) {
    const cand: ColKey[] = ["debit", "credit", "balance"];
    let best: ColKey = "balance";
    let bestD = Infinity;
    for (const k of cand) {
      const d = Math.abs(right - c[k].right);
      if (d < bestD) {
        bestD = d;
        best = k;
      }
    }
    return best;
  }
  // References are never dates, so a date right of the narration is the value date
  // even when the reference cell crowds it leftwards.
  if (SLASH_DATE.test(s) && it.x >= c.ref.left - 2) return "valueDate";
  if (it.x < c.narration.left - 2) return "date";
  if (it.x < c.ref.left - 2) return "narration";
  if (it.x < c.valueDate.left - 2) return "ref";
  // Non-numeric text spilling right of the value date is still narration.
  return "narration";
}

function newRow(index: number, txnDate: string): ParsedRow & { _narr: string[]; _ref: string[]; _raw: string[] } {
  return {
    rowIndex: index,
    txnDate,
    valueDate: null,
    description: "",
    referenceNumber: null,
    chequeNumber: null,
    debit: 0,
    credit: 0,
    balance: null,
    rawText: "",
    _narr: [],
    _ref: [],
    _raw: [],
  };
}

type Draft = ReturnType<typeof newRow>;

function finish(d: Draft): ParsedRow {
  const ref = d._ref.join("").trim() || null;
  return {
    rowIndex: d.rowIndex,
    txnDate: d.txnDate,
    valueDate: d.valueDate,
    description: d._narr.join(" ").replace(/\s+/g, " ").trim(),
    referenceNumber: ref,
    // Filled at import, once the narration is classified as a cheque.
    chequeNumber: null,
    debit: d.debit,
    credit: d.credit,
    balance: d.balance,
    rawText: d._raw.join("\n"),
  };
}

/** The header block: account number and statement period, wherever they sit. */
export function readHeaderFacts(lines: Line[]): { accountNumber: string | null; periodStart: string | null; periodEnd: string | null } {
  let accountNumber: string | null = null;
  let periodStart: string | null = null;
  let periodEnd: string | null = null;
  for (const l of lines) {
    if (!accountNumber) {
      const m = /Account\s*No\.?\s*:?\s*([0-9Xx*]{6,24})/i.exec(l.text);
      if (m) accountNumber = m[1];
    }
    if (!periodStart) {
      const m = /From\s*:?\s*(\d{2}\/\d{2}\/\d{2,4})\s*To\s*:?\s*(\d{2}\/\d{2}\/\d{2,4})/i.exec(l.text);
      if (m) {
        periodStart = parseSlashDate(m[1]);
        periodEnd = parseSlashDate(m[2]);
      }
    }
  }
  return { accountNumber, periodStart, periodEnd };
}

/** The STATEMENT SUMMARY figures, read from the first numeric line after its labels. */
export function readSummary(lines: Line[]): StatementSummary | null {
  const at = lines.findIndex((l) => /Opening\s*Balance/i.test(l.text) && /Closing/i.test(l.text));
  if (at < 0) return null;
  for (const l of lines.slice(at + 1, at + 4)) {
    const tokens = l.text.split(/\s+/);
    const amounts = tokens.filter((t) => isAmountToken(t)).map((t) => amountOf(t) as Paise);
    const counts = tokens.filter((t) => /^\d+$/.test(t)).map(Number);
    if (amounts.length === 4) {
      return {
        openingBalance: amounts[0],
        totalDebit: amounts[1],
        totalCredit: amounts[2],
        closingBalance: amounts[3],
        debitCount: counts.length >= 2 ? counts[0] : null,
        creditCount: counts.length >= 2 ? counts[1] : null,
      };
    }
  }
  return null;
}

function base(lines: Line[], strategy: string): ParsedStatement {
  const facts = readHeaderFacts(lines);
  const summary = readSummary(lines);
  return {
    bankCode: "HDFC",
    strategy,
    accountNumber: facts.accountNumber,
    periodStart: facts.periodStart,
    periodEnd: facts.periodEnd,
    openingBalance: summary?.openingBalance ?? null,
    closingBalance: summary?.closingBalance ?? null,
    summary,
    rows: [],
    anomalies: [],
    warnings: [],
  };
}

/** Primary: place every item by the page's column headers. */
export function parseByColumns(lines: Line[]): ParsedStatement {
  const out = base(lines, "columns");
  let cols: Columns | null = null;
  let inBody = false;
  let cur: Draft | null = null;
  let sawHeader = false;
  const flush = () => {
    if (cur) out.rows.push(finish(cur));
    cur = null;
  };

  const bands = findHeaderBands(lines);
  if (bands.some((b) => !b.cols)) throw new Error("HDFC column header not recognised");
  const bandAt = new Map<number, HeaderBand>();
  for (const b of bands) for (let i = b.start; i <= b.end; i++) bandAt.set(i, b);

  let page = -1;
  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    if (line.page !== page) {
      page = line.page;
      inBody = false;
    }
    const band = bandAt.get(li);
    if (band) {
      cols = band.cols;
      inBody = true;
      sawHeader = true;
      continue;
    }
    if (!inBody || !cols) continue;
    if (FOOTER.test(line.text)) {
      // Not a flush: a narration can carry on past the page footer onto the
      // next page, under that page's repeated header.
      inBody = false;
      continue;
    }

    const byCol = new Map<ColKey, TextItem[]>();
    for (const it of tokenize(line.items)) {
      const k = columnOf(it, cols);
      byCol.set(k, [...(byCol.get(k) ?? []), it]);
    }
    const dateText = (byCol.get("date") ?? []).map((i) => i.str.trim()).join("");
    const startsRow = SLASH_DATE.test(dateText);

    if (startsRow) {
      flush();
      const iso = parseSlashDate(dateText);
      if (!iso) {
        out.anomalies.push(`Unreadable transaction date "${dateText}"`);
        continue;
      }
      cur = newRow(out.rows.length, iso);
    } else if (!cur) {
      // Text between the header and the first dated row (e.g. "Opening balance" banners).
      continue;
    } else if (byCol.has("date")) {
      // Something in the date column that is not a date — the body has ended.
      flush();
      inBody = false;
      continue;
    }

    const row = cur!;
    row._raw.push(line.text);
    for (const it of byCol.get("narration") ?? []) row._narr.push(it.str.trim());
    for (const it of byCol.get("ref") ?? []) row._ref.push(it.str.trim());
    const vd = (byCol.get("valueDate") ?? []).map((i) => i.str.trim()).join("");
    if (vd) {
      const iso = parseSlashDate(vd);
      if (iso) row.valueDate = iso;
      else row._narr.push(vd);
    }
    for (const [k, field] of [
      ["debit", "debit"],
      ["credit", "credit"],
      ["balance", "balance"],
    ] as const) {
      const toks = byCol.get(k) ?? [];
      if (toks.length === 0) continue;
      if (toks.length > 1 || (field !== "balance" && row[field]) || (field === "balance" && row.balance !== null)) {
        out.anomalies.push(`Row ${row.rowIndex + 1} (${row.txnDate}) has more than one value in the ${k} column`);
      }
      const v = amountOf(toks[toks.length - 1].str);
      if (v === null) continue;
      if (field === "balance") row.balance = v;
      else row[field] = Math.abs(v);
    }
  }
  flush();

  if (!sawHeader) throw new Error("no HDFC column header found");
  reconcileDirections(out.rows, out.openingBalance, out.anomalies);
  return out;
}

/**
 * Fallback: each transaction's first line read as a string —
 *   dd/mm/yy  <narration> <ref>  dd/mm/yy  <amount>  <balance>
 * Direction comes from the running balance alone, which is why it needs the
 * opening balance (from the summary) to place the first row.
 */
export function parseByText(lines: Line[]): ParsedStatement {
  const out = base(lines, "text");
  const ROW = /^(\d{2}\/\d{2}\/\d{2,4})\s+(.+?)\s+(\d{2}\/\d{2}\/\d{2,4})\s+((?:\d{1,3}(?:,\d{2,3})*|\d+)\.\d{2})(?:\s+((?:\d{1,3}(?:,\d{2,3})*|\d+)\.\d{2}))?\s+(-?(?:\d{1,3}(?:,\d{2,3})*|\d+)\.\d{2})$/;
  const HEADER = /Narration.*(Withdrawal|Debit).*Balance/i;
  let inBody = false;
  let sawHeader = false;
  let cur: Draft | null = null;
  const flush = () => {
    if (cur) out.rows.push(finish(cur));
    cur = null;
  };
  let prev = out.openingBalance;

  const bandLines = new Set<number>();
  for (const b of findHeaderBands(lines)) for (let i = b.start; i <= b.end; i++) bandLines.add(i);

  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    if (bandLines.has(li) || HEADER.test(line.text)) {
      inBody = true;
      sawHeader = true;
      continue;
    }
    if (!inBody) continue;
    if (FOOTER.test(line.text)) {
      // Not a flush: a narration can carry on past the page footer onto the
      // next page, under that page's repeated header.
      inBody = false;
      continue;
    }
    const m = ROW.exec(line.text);
    if (m) {
      flush();
      const iso = parseSlashDate(m[1]);
      if (!iso) {
        out.anomalies.push(`Unreadable transaction date "${m[1]}"`);
        continue;
      }
      cur = newRow(out.rows.length, iso);
      const middle = m[2].split(" ");
      const last = middle[middle.length - 1];
      if (middle.length > 1 && /^(\d{6,}|[A-Z0-9]{10,})$/.test(last)) {
        cur._ref.push(last);
        middle.pop();
      }
      cur._narr.push(middle.join(" "));
      cur.valueDate = parseSlashDate(m[3]);
      cur._raw.push(line.text);
      const balance = amountOf(m[6]);
      cur.balance = balance;
      if (m[5]) {
        // Two amounts on one line: both a withdrawal and a deposit. Not something to guess at.
        out.anomalies.push(`Row ${cur.rowIndex + 1} (${iso}) shows two amounts`);
        cur.debit = amountOf(m[4]) ?? 0;
        cur.credit = amountOf(m[5]) ?? 0;
      } else {
        const amount = amountOf(m[4]) ?? 0;
        if (prev !== null && balance !== null && balance - prev === amount) cur.credit = amount;
        else if (prev !== null && balance !== null && prev - balance === amount) cur.debit = amount;
        else {
          out.anomalies.push(`Row ${cur.rowIndex + 1} (${iso}) direction could not be established from the balance`);
          cur.debit = amount;
        }
      }
      if (balance !== null) prev = balance;
      continue;
    }
    if (cur) {
      cur._narr.push(line.text);
      cur._raw.push(line.text);
    }
  }
  flush();
  if (!sawHeader) throw new Error("no HDFC column header found");
  return out;
}

export class HDFCStatementParser extends BaseBankStatementParser {
  readonly bankCode = "HDFC";
  protected strategies() {
    return [
      { name: "columns", run: parseByColumns },
      { name: "text", run: parseByText },
    ];
  }
}
